// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/chalermridp/go-template-rest/internal/app/controller"
	"github.com/chalermridp/go-template-rest/internal/app/repository"
	"github.com/chalermridp/go-template-rest/internal/app/service"
	"github.com/google/wire"
)

// Injectors from injector.go:

func Init() *Initialization {
	defaultUserRepository := repository.NewUserRepository()
	defaultUserService := service.NewUserService(defaultUserRepository)
	defaultUserController := controller.NewUserController(defaultUserService)
	initialization := NewInitialization(defaultUserController, defaultUserService, defaultUserRepository)
	return initialization
}

// injector.go:

var userRepoSet = wire.NewSet(repository.NewUserRepository, wire.Bind(new(repository.UserRepository), new(*repository.DefaultUserRepository)))

var userServiceSet = wire.NewSet(service.NewUserService, wire.Bind(new(service.UserService), new(*service.DefaultUserService)))

var userControllerSet = wire.NewSet(controller.NewUserController, wire.Bind(new(controller.UserController), new(*controller.DefaultUserController)))
